# https://www.udemy.com/course/microservices-with-node-js-and-react/learn/lecture/19102628#questions/13076054
apiVersion: skaffold/v2beta4
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: avgsteve/ticket-auth
      context: auth
      sync:
        infer:
          - 'src/**/*.ts'
        # manual:
        #   - src: "src/**/*.ts"
        #     dest: .
    - image: avgsteve/ticket-client
      context: client
      sync:
        infer:
          - 'src/**/*.js'
    - image: avgsteve/ticket-tickets
      context: tickets
      sync:
        infer:
          - 'src/**/*.ts'          
        # manual:
        #   - src: "src/**/*.ts"
        #     dest: .
    - image: avgsteve/ticket-orders
      context: orders
      sync:
        infer:
          - 'src/**/*.ts'       
    - image: avgsteve/ticket-expiration
      context: expiration
      sync:
        infer:
          - 'src/**/*.ts'          
    - image: avgsteve/ticket-payments
      context: payments
      sync:
        infer:
          - 'src/**/*.ts'                     

# # 進行發布 的 .yaml 檔案資料夾
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8s/*
#       - ./infra/k8s-dev/*

# 發布的設定跟發布內容
# profiles:
#   - name: cloudbuild
#     build:
#       googleCloudBuild: { projectId: ticket-dev-303913 }
#       # projectId: ticket-dev-303913
#       artifacts:
# # Auth service
#         - image: avgsteve/ticket-auth
#           context: auth
#           docker:
#             dockerfile: Dockerfile
#           sync:
#             infer:
#               - 'src/**/*.ts'
#             # manual:
#             #   - src: "src/**/*.ts"
#             #     dest: .
# # Client service
#         - image: avgsteve/ticket-client           
#           context: client
#           docker:
#             dockerfile: Dockerfile
#           sync:
#             infer:
#               - '**/*.js'
# # Tickets service
#         - image: avgsteve/ticket-tickets           
#           context: tickets
#           docker:
#             dockerfile: Dockerfile
#           sync:
#             infer:
#               - '**/*.ts'              
# # Order service
#         - image: avgsteve/ticket-orders           
#           context: orders
#           docker:
#             dockerfile: Dockerfile
#           sync:
#             infer:
#               - '**/*.ts'              
# # Expiration service
#         - image: avgsteve/ticket-expiration           
#           context: expiration
#           docker:
#             dockerfile: Dockerfile
#           sync:
#             infer:
#               - '**/*.ts'        
# # Payment service
#         - image: avgsteve/ticket-payments           
#           context: payments
#           docker:
#             dockerfile: Dockerfile
#           sync:
#             infer:
#               - '**/*.ts'                         