name: deploy-orders
on: 
  push:
    branches:
      - master
    paths:
      - 'orders/**'

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        
      # build image        
      - run: cd orders && docker build -t avgsteve/ticketing-orders .
        
      # login to docker
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
      # push image to docker hub
      - run: docker push avgsteve/ticketing-orders
        
      # use and ordersenticate doctl  
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      
      # give credential to k8s cluster
      - run: doctl kubernetes cluster kubeconfig save ticketing
      
      # restart deployment
      - run: kubectl rollout restart deployment orders-depl

